config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  root 'homes#top'
  get 'home/about' => 'homes#about'

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  devise_for :users

  resources :users, only: [:show, :index, :edit, :update] do
    member do
      get :following, :followers
    end
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]

  get '/search' => 'search#search'

  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  get 'rakuten_search' => 'search#index'
end

app/models/search_form.rb
class SearchForm
  include ActiveModel::Model

  attr_accessor :keyword

  # VALID_KEYWORD_REGEX = /\A(?:\p{Hiragana}|\p{Katakana}|[ー－]|[一-龠々])+\z/
  validates :keyword, presence: true, length: { in: 2..20 }
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @model = params["search"]["model"]
    @content = params["search"]["content"]
    @how = params["search"]["how"]
    @datas = search_for(@how, @model, @content)
  end

  # 楽天API商品検索
  def index
    if params[:keyword]
      items = SearchForm.new(keyword: params[:keyword])
      if items.valid?
        @items = RakutenWebService::Ichiba::Item.search(keyword: items.keyword)
      else
        flash[:danger] = "検索ワードは日本語2文字以上で入力してください(数字NG)"
        redirect_to rakuten_search_path
      end
    end
  end

  private

  def match(model, content)
    if model == 'Users'
      User.where(name: content)
    elsif model == 'Books'
      Book.where(title: content)
    end
  end

  def forward(model, content)
    if model == 'Users'
      User.where("name LIKE?", "#{content}%")
    elsif model == 'Books'
      Book.where("title LIKE?", "#{content}%")
    end
  end

  def backward(model, content)
    if model == 'Users'
      User.where("name LIKE?", "%#{content}")
    elsif model == 'Books'
      Book.where("titile LIKE?", "%#{content}")
    end
  end

  def partial(model, content)
    if model == 'Users'
      User.where("name LIKE?", "%#{content}%")
    elsif model == 'Books'
      Book.where("title LIKE?", "%#{content}%")
    end
  end

  def search_for(how, model, content)
    case how
    when 'match'
      match(model, content)
    when 'forward'
      forward(model, content)
    when 'backward'
      backward(model, content)
    when 'partial'
      partial(model, content)
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <div class="rakuten-search_box rakuten_search">
        <%= form_with url: rakuten_search_path, method: :get, local: true, class: "d-flex w-75 float-right rankuten_search_form" do |f| %>
          <%= f.text_field 'keyword', placeholder: "検索ワードを2文字以上で入力...", class: "rakuten-search-form form-control form-control-lg" %>
          <%= f.submit "検索", class: "rakuten-search-btn btn btn-dark rakuten_kensaku_button" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="alert">
  <%= flash[:danger] %>
</div>
    <% if @items.present? %>
      <div class="container-fluid">
        <div class="row">
          <% @items.each do |item| %>
            <div class="col-lg-3 rakuten_items bg-light text-dark text-center col-sm-12">
                  <%= link_to "#{item.url}", target: :_blank do %>
                        <%= image_tag item["mediumImageUrls"][0] %>
                        <div class="text-left">
                          <ul>
                            <li><%= item.name %></li>
                            <li><%= item.price %>円</li>
                          </ul>
                        </div>
                  <% end %>
            </div>
          <% end %>
        </div>
      </div>
    <% else %>
      <p>該当する商品はありません</p>
    <% end %>
<div class="float-right h1 p-3 mb-2 bg-dark search_tops_button rounded">
  <a href="#" class="scroll-btn-post">
    <i class="fas fa-long-arrow-alt-up text-white"></i>
  </a>
</div>

app/views/search/search.html.erb
<h2><%= "#{@model} search for \"#{@content}\"" %> </h2>
<% if @datas.blank?  %>
<p>該当データはありません</p>
<% else %>
  <% if @model == "Users" %>
    <table class='table'>
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @datas.each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, fallback: "no-image-icon.jpg", size: "50x50" %></td>
            <td><%= user.name %></td>
            <td><%= "フォロー数：#{user.following.count}" %></td>
            <td><%= "フォロワー数：#{user.followers.count}" %></td>
            <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <% elsif @model = "Books" %>
    <table class='table'>
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="2"></th>
        </tr>
      </thead>
      <tbody>
        <% @datas.each do |book| %>
          <tr>
            <td><%= attachment_image_tag book.user, :profile_image, fallback: "no-image-icon.jpg", size: "50x50" %></td>
            <td><%= link_to "#{book.title}", book_path(book) %></td>
            <td><%= book.body %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <% end %>
<% end %>