config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  root 'homes#top'
  get 'home/about' => 'homes#about'

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  devise_for :users

  resources :users, only: [:show, :index, :edit, :update] do
    member do
      get :following, :followers
    end
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]

  get '/search' => 'search#search'

  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  get 'rakuten_search' => 'search#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  attachment :profile_image, destroy: false

  validates :name, length: { maximum: 20, minimum: 2 }, uniqueness: true
  validates :introduction, length: { maximum: 500 }

  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :active_relationships,  class_name: "Relationship",
                                   foreign_key: "follower_id",
                                   dependent: :destroy

  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy

  has_many :following,                through: :active_relationships,
                                      source: :followed

  has_many :followers,                through: :passive_relationships,
                                      source: :follower

  # ユーザーをフォローする　<＜は配列に追加の意味
  def follow(other_user)
    following << other_user
  end

  # ユーザーのフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしていたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms

  # guestログイン
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |end_user|
      end_user.password = SecureRandom.urlsafe_base64
      end_user.name = "ゲスト太郎"
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def following
    @user = User.find(params[:id])
    @users = @user.following
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td class="iphone_none"><%= "フォロー数：#{user.following.count}" %></td>
        <td class="iphone_none"><%= "フォロワー数：#{user.followers.count}" %></td>
        <td>
          <% unless current_user == user %>
          <% if fid = current_user.active_relationships.find_by(followed_id: user.id) %>
            <%= link_to "フォローを外す", relationship_path(fid.id), method: :delete,class: "btn btn-light" %>
          <% else %>
            <%= link_to "フォローする", relationships_path(followed_id: user.id), method: :post, class: "btn btn-dark" %>
          <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id} btn btn-light" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to "#{user.following.count}", following_user_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to "#{user.followers.count}", followers_user_path(user) %></th>
  </tr>


</table>

<% unless current_user == user %>
<div class="follow_form">
  <% if current_user.following?(user) %>
    <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id), method: :delete, local: true) do |f| %>
    <%= hidden_field_tag :id, user.id %>
    <%= f.submit "フォローを外す", class: "btn btn-primary" %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.active_relationships.build, local: true) do |f| %>
    <%= hidden_field_tag :followed_id, user.id %>
    <%= f.submit"フォローする", class: "btn btn-dark follow_form_button" %>
    <% end %>
  <% end %>
</div>
<% end %>

<% if current_user == user %>
<div>
  <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
</div>
<% end %>

<% if current_user != user %>
  <%= link_to 'チャットする', chat_path(user.id) , class: "btn btn-light"%>
<% end %>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<h2>Follower Users</h2>
    <% if @users.blank?  %>
<p>ユーザーはいません</p>
<% else %>
    <table class='table'>
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, fallback: "no-image-icon.jpg", size: "50x50" %></td>
            <td><%= user.name %></td>
            <td><%= "フォロー数：#{user.following.count}" %></td>
            <td><%= "フォロワー数：#{user.followers.count}" %></td>
            <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
<% end %>

app/views/users/following.html.erb
<h2>Follow Users</h2>
    <% if @users.blank?  %>
<p>ユーザーはいません</p>
<% else %>
    <table class='table'>
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, fallback: "no-image-icon.jpg", size: "50x50" %></td>
            <td><%= user.name %></td>
            <td><%= "フォロー数：#{user.following.count}" %></td>
            <td><%= "フォロワー数：#{user.followers.count}" %></td>
            <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
<% end %>

app/views/users/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>

    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>