config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  root 'homes#top'
  get 'home/about' => 'homes#about'

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  devise_for :users

  resources :users, only: [:show, :index, :edit, :update] do
    member do
      get :following, :followers
    end
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]

  get '/search' => 'search#search'

  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  get 'rakuten_search' => 'search#index'
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 500 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<tr>
    <td>
      <%= link_to user_path(book.user) do %>
      <%= attachment_image_tag book.user, :profile_image, fallback: "no-image-icon.jpg", size: "50x50" %>
      <% end %>
    </td>
    <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
    <td><%= book.body %></td>
    <td id="favorite-btn-<%= book.id %>"><%= render 'favorite/favorite-btn', book: book %></td>
    <td><%= "コメント数：#{book.book_comments.count}" %></td>
</tr>

app/views/books/_comment.html.erb
<table>
  <% @book.book_comments.each do |book_comment| %>
    <% book_comment_user = book_comment.user %>
    <tr>
    	<td>
    		<%= link_to user_path(book_comment_user), class: "user_#{book_comment_user.id}" do %>
      		<%= attachment_image_tag book_comment_user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %><br>
      		<%= book_comment_user.name %>
    		<% end %>
    	</td>
    	<td><%= book_comment.comment %></td>
    	<% if current_user == book_comment_user %>
      	<td><%= link_to 'Destroy', book_book_comment_path(book_comment.book_id, book_comment.id), class: 'btn-sm btn-danger', method: :delete %></td>
    	<% end %>
    </tr>
  <% end %>
</table>
<%= form_with model:[@book,@book_comment], local: true do |f| %>
  <%= f.text_area :comment, size:"90x5" %>
  <%= f.submit '送信'%>
<% end %>

app/views/books/_commentform.html.erb
<% if @book_comment.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(@book_comment.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% @book_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_with  url: book_book_comments_path(book.id), remote: true do |f| %>
    <div class="form-group">
        <%= f.text_area :comment, class: 'form-control book_body' %>
    </div>
    <div class="form-group">
        <%= f.submit "送信", class: 'btn btn-light btn-outline-dark' %>
    </div>
<% end %>

app/views/books/_commentlist.html.erb
<% book.book_comments.each do |comment| %>
    <div class="comment-box">
        <div class="comment-user">
            <%= link_to user_path(comment.user) do %>
            <%= attachment_image_tag comment.user, :profile_image, fallback: "no-image-icon.jpg", size: "50x50" %><br>
            <%= comment.user.name %>
            <% end %>
        </div>
        <div class="comment-text">
            <%= comment.comment %>
        </div>
        <% if comment.user == current_user %>
        <div class="comment-delete-button">
            <%= link_to 'Destroy', book_book_comment_path(comment.book.id, comment.id), method: :delete, remote: true, class: "btn btn-sm btn-danger" %>
        </div>
        <% end %>
    </div>
<% end %>

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-dark' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<% books.each do |book| %>
  <div class="books_index p-3 mb-2 bg-light text-dark shadow">
      <%= link_to user_path(book.user) do %>
        <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
      <% end %>
      <div class="pt-3 pl-5 w-100 books_index_items text-dark">
        <p class="h1 pb-3"><span><%= link_to book.title, book_path(book), class: "book_#{book.id} text-dark" %></span></p>
        <p class="h3"><%= book.body %></p>
        <div class="d-flex justify-content-end">
          <p id="favorite-btn-<%= book.id %>" class="pr-4 h4 text-dark">
            <%= render "favorites/favorite-btn", book: book, class: "text-dark" %>
          </p>
          <p class="h4">コメント数: <%= book.book_comments.count %></p>
        </div>
      </div>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: Book.new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
  		    <td><%= link_to user_path(@book.user) do %>
            <%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
          <td id="favorite-btn-<%= @book.id %>"><%= render 'favorites/favorite-btn', book: @book %></td>
          <td id="bookcomment-number"><%= "コメント数：#{@book.book_comments.count}" %></td>
          
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
        </tr>
      </table>
      
      <div class="commentlist-box-<%= @book.id %>"><%= render 'books/commentlist', book: @book %></div>
      <div class="commentform-box-<%= @book.id %>"><%= render 'books/commentform', book: @book %></div>
    
    </div>
  </div>
</div>